import Head from 'next/head'
import SignInForm from '../components/SignInForm.js'
import styled from 'styled-components'


const Container = styled.div`
    display: flex;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 100%;
    height: 100%;
    background-color: white;
`

const Wrapper = styled.div`
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    max-width: 400px;
    height: auto;
    background-color: gray;
    margin: auto;
    border-radius: 15px;
`

export default function Home() {
  return (
    <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Wrapper>
          <SignInForm />
        </Wrapper>

    </Container>
  )
}
