import { useState } from 'react'
import Head from 'next/head'
import styled from 'styled-components'
import SignUpForm from '../components/SignUpForm.js'
import LogIn from '../components/LogIn.js'
import { useRouter } from 'next/router'

import { useAuth } from '../contexts/AuthContext'

const Container = styled.div`
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    width: 100vw;
    height: 100vh;
    overflow: none;
`

const Wrapper = styled.div`
    display: flex;
    position: relative;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    max-width: 400px;
    height: 450px;
    background-color: gray;
    margin: auto;
    border-radius: 15px;
`

const LeftBox = styled.div`
    display: flex;
    width: 50%;
    height: 100vh;
    background-image: url('/images/football.jpg');
    background-position: center top;
    background-size: cover;
    background-repeat: no-repeat;
`

const RightBox = styled.div`
    display: flex;
    flex-direction: column;
    width: 50%;
    height: 100vh;
    background-color: #123222 ;
`

const TextBox = styled.div`
    position: absolute;
    top: 0;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    padding-top: 30px;
`

const Text = styled.p`
    text-align: center;
    cursor: pointer;
`

const Message = styled.p`
    position: absolute;
    bottom: 5%;
    font-weight: 500;
    letter-spacing: 1px;
    height: 30px;
    text-align: center;
    padding-top: 10px;
    padding-bottom: 10px;
`

export default function Home() {
  const [login, setLogin] = useState(true)
  const [message, setMessage] = useState("Not Signed In")
  const router = useRouter()
  const { currentUser, error, setError } = useAuth()

  if(currentUser != null){
    router.push('/dashboard')
  }

  return (
    <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <LeftBox />

        <RightBox>
          <Wrapper>
            <TextBox>
              <Text 
                style={{ color: login ? 'black' : 'white', textDecoration: login ? 'none' : 'underline' }}
                onClick={e => {
                  setLogin(false);
                  setError('');
                }}
              > 
                Sign Up
              </Text>
              <Text
                style={{ color: login ? 'white' : 'black', textDecoration: login ? 'underline' : 'none' }}
                onClick={e => {
                  setLogin(true);
                  setError('');
                }}
              >
                Log In 
              </Text>
            </TextBox>
            {login ? 
              <LogIn error={error} setError={setError}/> 
              : 
              <SignUpForm error={error} setError={setError} setMessage={setMessage}/> 
            }

            {error.length > 0 ?
                    <Message> {error} </Message> : <Message> {currentUser?.email || 'Not Logged In'} </Message> 
            } 

          </Wrapper>
        </RightBox>

    </Container>
  )
}

